In [1]:
import numpy as np

In [26]:
def metryka_minkowskiego(x,y,p):
    if p >=1 and p != float('inf'):
        wynik = (np.sum((abs(x-y))**p))**(1/p)
    elif p < 1 and p >= 0:
        wynik = np.sum(abs((x-y))**p)
    elif p == float('inf'):
        wynik = np.max(abs(x-y))
    return wynik

def macierz_odleglosci(x,p):
    rozmiar = len(x)
    D = np.zeros((rozmiar,rozmiar))
    for i in range(len(x)):
        for j in range(i,len(x)):
            D[j,i] = D[i,j] = metryka_minkowskiego(x[i],x[j],p)
    return print(f"Macierz odległości dla p = {p} wygląda następująco:\n{np.round(D,2)},\na średnica zbioru:\n{np.max(D)}")

def odleglosc_miedzy_zbiorami(x,y,p):
    rozmiar_x = len(x)
    rozmiar_y = len(y)
    D = np.zeros((rozmiar_x,rozmiar_y))
    for i in range(len(x)):
        for j in range(len(y)):
            D[i,j] = metryka_minkowskiego(x[i],y[j],p)
    return print(f'Odległośc dla p = {p} między tymi zbiorami wynosi:\n{np.min(D)}')

x = np.round(np.random.random_sample(10)*10)
y = np.round(np.random.random_sample(10)*10)
z = np.round(np.random.random_sample(10)*10)
w = np.round(np.random.random_sample(10)*10)

a = np.round(np.random.random_sample(10)*10)
b = np.round(np.random.random_sample(10)*10)
c = np.round(np.random.random_sample(10)*10)
d = np.round(np.random.random_sample(10)*10)

X = np.array([x,y,z,w])
Y = np.array([a,b,c,d])

macierz_odleglosci(X,5)

macierz_odleglosci(Y,2)

odleglosc_miedzy_zbiorami(X,Y,3)

Macierz odległości dla p = 5 wygląda następująco:
[[ 0.    5.6  10.4   6.86]
 [ 5.6   0.   10.22  6.36]
 [10.4  10.22  0.    6.59]
 [ 6.86  6.36  6.59  0.  ]],
a średnica zbioru:
10.404948191522992
Macierz odległości dla p = 2 wygląda następująco:
[[ 0.   15.78 10.1  14.56]
 [15.78  0.   14.93 16.28]
 [10.1  14.93  0.   14.42]
 [14.56 16.28 14.42  0.  ]],
a średnica zbioru:
16.278820596099706
Odległośc dla p = 3 między tymi zbiorami wynosi:
6.333025531362916


In [28]:
test = "abecadlo"
test

'abecadlo'

In [30]:
test[:-4]

'abec'