In [1]:
import numpy as np

In [26]:
def metryka_minkowskiego(x,y,p):
    if p >=1 and p != float('inf'):
        wynik = (np.sum((abs(x-y))**p))**(1/p)
    elif p < 1 and p >= 0:
        wynik = np.sum(abs((x-y))**p)
    elif p == float('inf'):
        wynik = np.max(abs(x-y))
    return wynik

def macierz_odleglosci(x,p):
    rozmiar = len(x)
    D = np.zeros((rozmiar,rozmiar))
    for i in range(len(x)):
        for j in range(i,len(x)):
            D[j,i] = D[i,j] = metryka_minkowskiego(x[i],x[j],p)
    return print(f"Macierz odległości dla p = {p} wygląda następująco:\n{np.round(D,2)},\na średnica zbioru:\n{np.max(D)}")

def odleglosc_miedzy_zbiorami(x,y,p):
    rozmiar_x = len(x)
    rozmiar_y = len(y)
    D = np.zeros((rozmiar_x,rozmiar_y))
    for i in range(len(x)):
        for j in range(len(y)):
            D[i,j] = metryka_minkowskiego(x[i],y[j],p)
    return print(f'Odległośc dla p = {p} między tymi zbiorami wynosi:\n{np.min(D)}')

x = np.round(np.random.random_sample(10)*10)
y = np.round(np.random.random_sample(10)*10)
z = np.round(np.random.random_sample(10)*10)
w = np.round(np.random.random_sample(10)*10)

a = np.round(np.random.random_sample(10)*10)
b = np.round(np.random.random_sample(10)*10)
c = np.round(np.random.random_sample(10)*10)
d = np.round(np.random.random_sample(10)*10)

X = np.array([x,y,z,w])
Y = np.array([a,b,c,d])

macierz_odleglosci(X,5)

macierz_odleglosci(Y,2)

odleglosc_miedzy_zbiorami(X,Y,3)

Macierz odległości dla p = 5 wygląda następująco:
[[ 0.    5.6  10.4   6.86]
 [ 5.6   0.   10.22  6.36]
 [10.4  10.22  0.    6.59]
 [ 6.86  6.36  6.59  0.  ]],
a średnica zbioru:
10.404948191522992
Macierz odległości dla p = 2 wygląda następująco:
[[ 0.   15.78 10.1  14.56]
 [15.78  0.   14.93 16.28]
 [10.1  14.93  0.   14.42]
 [14.56 16.28 14.42  0.  ]],
a średnica zbioru:
16.278820596099706
Odległośc dla p = 3 między tymi zbiorami wynosi:
6.333025531362916


In [28]:
test = "abecadlo"
test

'abecadlo'

In [30]:
test[:-4]

'abec'

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('iris.csv')

In [3]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [11]:
df.query('species == "setosa"')

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
5,5.4,3.9,1.7,0.4,setosa
6,4.6,3.4,1.4,0.3,setosa
7,5.0,3.4,1.5,0.2,setosa
8,4.4,2.9,1.4,0.2,setosa
9,4.9,3.1,1.5,0.1,setosa


In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('northwind.db')

query = "select * from categories"
pd.read_sql_query(query, conn)

,CategoryID,CategoryName,Description,Picture
0,1,Beverages,"Soft drinks, coffees, teas, beers, and ales",b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
1,2,Condiments,"Sweet and savory sauces, relishes, spreads, an...",b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
2,3,Confections,"Desserts, candies, and sweet breads",b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
3,4,Dairy Products,Cheeses,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
4,5,Grains/Cereals,"Breads, crackers, pasta, and cereal",b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
5,6,Meat/Poultry,Prepared meats,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
6,7,Produce,Dried fruit and bean curd,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
7,8,Seafood,Seaweed and fish,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...


In [ ]:
pd.