https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.1+cpu


In [ ]:
#!nvidia-smi


In [4]:
#Create a tensor
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
# help(torch.tensor)

In [7]:
scalar.ndim

0

In [9]:
scalar.item()

7

In [10]:
vector = torch.tensor([7, 10])

In [21]:
vector.ndim, vector.shape, vector.size(), vector.dtype, vector.type(), vector.device, vector.requires_grad, vector.is_floating_point(), vector.is_complex(), vector.is_signed()

(1,
 torch.Size([2]),
 torch.Size([2]),
 torch.int64,
 'torch.LongTensor',
 device(type='cpu'),
 False,
 False,
 False,
 True)

In [22]:
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [23]:
MATRIX.ndim, MATRIX.shape, MATRIX.size(), MATRIX.dtype, MATRIX.type(), MATRIX.device, MATRIX.requires_grad, MATRIX.is_floating_point(), MATRIX.is_complex(), MATRIX.is_signed()

(2,
 torch.Size([2, 3]),
 torch.Size([2, 3]),
 torch.int64,
 'torch.LongTensor',
 device(type='cpu'),
 False,
 False,
 False,
 True)

In [25]:
MATRIX[1]

tensor([4, 5, 6])

In [27]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [28]:
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [29]:
TENSOR.ndim, TENSOR.shape, TENSOR.size(), TENSOR.dtype, TENSOR.type(), TENSOR.device, TENSOR.requires_grad, TENSOR.is_floating_point(), TENSOR.is_complex(), TENSOR.is_signed()

(3,
 torch.Size([1, 3, 3]),
 torch.Size([1, 3, 3]),
 torch.int64,
 'torch.LongTensor',
 device(type='cpu'),
 False,
 False,
 False,
 True)

In [45]:
TENSOR2 = torch.tensor([[[
    [[1,2,3], [4,5,6], [7,8,9],[10,11,12]],
    [[10,11,12], [13,14,15], [16,17,18],[19,20,21]]
    ]]])

In [46]:
TENSOR2.ndim, TENSOR2.shape, TENSOR2.size(), TENSOR2.dtype, TENSOR2.type(), TENSOR2.device, TENSOR2.requires_grad, TENSOR2.is_floating_point(), TENSOR2.is_complex(), TENSOR2.is_signed()

(5,
 torch.Size([1, 1, 2, 4, 3]),
 torch.Size([1, 1, 2, 4, 3]),
 torch.int64,
 'torch.LongTensor',
 device(type='cpu'),
 False,
 False,
 False,
 True)

In [47]:
### Random tensors

In [51]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3888, 0.0111, 0.5160, 0.6144],
        [0.9175, 0.3441, 0.1275, 0.6513],
        [0.3066, 0.8520, 0.4862, 0.1979]])

In [52]:
#help(torch.rand)

In [62]:
random_image_size_tensor = torch.rand(size=(3, 224, 224))

In [63]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 224, 224]))

In [65]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [67]:
torch.ones(size=(3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [70]:
torch.arange(0, 10, step=2)

tensor([0, 2, 4, 6, 8])

In [72]:
# help(torch.arange)

In [ ]:
torch.zeros_like(torch.arange(0, 11))

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Note** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & DL
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [76]:
#float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,
                                device=None,
                                requires_grad=False)
float_32_tensor.dtype

torch.float32

In [79]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

1. Tensors not right datatype - ``` tensor.dtype ```
2. Tensors not right shape - ``` tensor.shape ```
3. Tensors not on the right device - ```tensor.device ```

In [80]:
float_16_tensor.device

device(type='cpu')

In [84]:
tensor1 = torch.tensor([1, 2, 3])
tensor1 + 10

tensor([11, 12, 13])

In [86]:
tensor1 * 10

tensor([10, 20, 30])

In [87]:
tensor1 % 2

tensor([1, 0, 1])

In [88]:
tensor1 // 2

tensor([0, 1, 1])

In [89]:
torch.sub(tensor1, 10)

tensor([-9, -8, -7])

In [ ]:
torch.matmul(tensor1, tensor1) # 1*1 + 2*2 + 3*3 = 14 # dot to samo

tensor(14)

Matrix multiplication ```dot product ```

In [94]:
tensor1*tensor1

tensor([1, 4, 9])

In [96]:
torch.multiply(tensor1, tensor1) 

tensor([1, 4, 9])

In [ ]:
torch.matmul(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[5, 6], [7, 8]])) #torch.mm(A, B) is the same as torch.matmul(A, B)

tensor([[19, 22],
        [43, 50]])

In [104]:
tensor3 = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor3

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [114]:
tensor3.t(),tensor3.T, tensor3.t().shape 

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 tensor([[1, 3, 5],
         [2, 4, 6]]),
 torch.Size([2, 3]))

In [115]:
#tensor aggregation

In [132]:
x = torch.arange(1, 100, step=10)

In [133]:
torch.max(x), x.max(), x.argmax(), x.argmin(), x.min(), x.mean(), x.sum(), x.std(), x.var(), x.prod(), x.cumsum(dim=0), x.cumprod(dim=0)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [134]:
x = x.type(torch.float32)

In [135]:
torch.max(x), x.max(), x.argmax(), x.argmin(), x.min(), x.mean(), x.sum(), x.std(), x.var(), x.prod(), x.cumsum(dim=0), x.cumprod(dim=0)

(tensor(91.),
 tensor(91.),
 tensor(9),
 tensor(0),
 tensor(1.),
 tensor(46.),
 tensor(460.),
 tensor(30.2765),
 tensor(916.6667),
 tensor(4.7802e+14),
 tensor([  1.,  12.,  33.,  64., 105., 156., 217., 288., 369., 460.]),
 tensor([1.0000e+00, 1.1000e+01, 2.3100e+02, 7.1610e+03, 2.9360e+05, 1.4974e+07,
         9.1339e+08, 6.4851e+10, 5.2529e+12, 4.7802e+14]))

In [143]:
torch.tensor([1,2,3,4,5]).cumsum(dim=0)

tensor([ 1,  3,  6, 10, 15])

In [148]:
x.argmin()

tensor(0)

In [151]:
#reshaping, viewing, stacking and squeezing tensors
#squeeze - removes all dimensions of size 1 from a tensor
#unsqueeze - adds a dimension of size 1 to a tensor
#permute - return a view of the tensor with dimensions permuted in a specified order

In [153]:
y = torch.arange(1., 10.)
y,y.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [157]:
y_reshaped = y.reshape(1, 9)
y_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [161]:
y_reshaped.reshape(9,1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [163]:
y.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [164]:
y_reshaped.reshape(-1, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [166]:
z = y.view(3,3)
z

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [170]:
y[2] = 100
z

tensor([[  1.,   2., 100.],
        [  4.,   5.,   6.],
        [  7.,   8.,   9.]])

In [171]:
z[1] = 200
y

tensor([  1.,   2., 100., 200., 200., 200.,   7.,   8.,   9.])

In [179]:
y_stacked = torch.stack([y, y, y], dim=1)
y_stacked

tensor([[  1.,   1.,   1.],
        [  2.,   2.,   2.],
        [100., 100., 100.],
        [200., 200., 200.],
        [200., 200., 200.],
        [200., 200., 200.],
        [  7.,   7.,   7.],
        [  8.,   8.,   8.],
        [  9.,   9.,   9.]])

In [180]:
y_stacked = torch.stack([y, y, y], dim=0)
y_stacked

tensor([[  1.,   2., 100., 200., 200., 200.,   7.,   8.,   9.],
        [  1.,   2., 100., 200., 200., 200.,   7.,   8.,   9.],
        [  1.,   2., 100., 200., 200., 200.,   7.,   8.,   9.]])

In [181]:
y_reshaped.squeeze()

tensor([  1.,   2., 100., 200., 200., 200.,   7.,   8.,   9.])

In [184]:
print(f'before: {y_reshaped.shape}')
print(f'after: {y_reshaped.squeeze().shape}')

before: torch.Size([1, 9])
after: torch.Size([9])


In [185]:
y_squeezed = y_reshaped.squeeze()

In [191]:
# torch.unsqueze() - adds a dimension of size 1 to a tensor
print(f'before: {y_squeezed.shape}')
print(f'after: {y_squeezed.unsqueeze(dim=1).shape}')

before: torch.Size([9])
after: torch.Size([9, 1])


In [196]:
y_reshaped.permute(1,0)

tensor([[  1.],
        [  2.],
        [100.],
        [200.],
        [200.],
        [200.],
        [  7.],
        [  8.],
        [  9.]])

In [197]:
x_original = torch.rand(size=(224, 224, 3))

In [200]:
x_permuted = x_original.permute(1, 2, 0) # shifts axis 0->1, 1->2, 2->0

In [201]:
print(f'Previous shape: {x_original.shape}')
print(f'Permuted shape: {x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([224, 3, 224])


In [202]:
x_original[0, 0, 0] = 100
x_original[0, 0, 0], x_permuted[0, 0, 0] # should be the same value in both tensors

(tensor(100.), tensor(100.))

In [203]:
x = torch.arange(1, 10).reshape(1,3,3)

In [204]:
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [209]:
x[0], x[0,0], x[0,0,0] # x[9] is out of bounds, x[0,0] is the first element in the first row, x[0,0,0] is the first element in the first row of the first channel

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [211]:
x[0, :, 1]

tensor([2, 5, 8])

In [213]:
torch.from_numpy(np.array([1,2,3]))

tensor([1, 2, 3])

In [217]:
x.numpy()

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [218]:
tensor = torch.ones(5)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [219]:
tensor += 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [224]:
## reproducibility (trying to take random out of random)


torch.manual_seed(42) # works only for one next using
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A == random_tensor_B) 


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
torch.manual_seed(42) # works only for one next using
random_tensor_A = torch.rand(3, 4)
torch.manual_seed(42) # works only for one next using
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A == random_tensor_B) 

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
